### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ChiaraBi** [ChiaraBi/vision-project#1]
- Modelli
  - [x] Zhang et al.
  - [x] Dahl
  - [x] Vitoria et al., ChromaGAN
  - [x] Su et al. (https://arxiv.org/abs/2005.10825)

- Dataset
  - [x] ImageNet (church, cani, tench, parachute, garbage truck)
  - [x] Places
  - [x] Pascal
  - [x] birds (ostrich, pink robin, tuchan, nicobar pigeon, fire tailled myzornis, flamingo, cuban tody, bald eagle)
  - [x] flowers

- Immagini modificate: selezionare 5 o 6 classi, 4 o 3 immagini per classe, per un totale di circa 20 immagini (No Su)
  - [x] blurring 
  - [x] contrasto
  - [x] luminosità
  - [x] cartoon (https://github.com/SystemErrorWang/White-box-Cartoonization) (https://cartoonize-lkqov62dia-de.a.run.app/cartoonize)

- Baseline autoencoder:
  - [x] final_output = channel_l(img_original) + channel_ab(img_cartoon ricolorata)

- Metriche
  - [x] Classification accuracy (difference between original and recolorized images)
  - [x] LPIPS: https://github.com/richzhang/PerceptualSimilarity 
  - [x] PSNR and SSIM: https://cvnote.ddlee.cc/2019/09/12/psnr-ssim-python  

- Turing test
  - [x] Confronto: 3 BW + 4 colored con rating 5 stelle

- Tasks (finetuning su BW + confronto dei risultati BW vs colorized)
  - [x] Classification on ImageNet
  - [x] Classification on Birds and Flowers

**Comment by ChiaraBi** [comment]
Immagini modificate:

- più si aumenta il blurring, peggiore è la colorization
- le immagini vengono colorate meglio con un contrasto elevato, salvo alcune eccezioni
- le immagini vengono colorate meglio con una luminosità elevata, salvo alcune eccezioni

**Comment by ChiaraBi** [comment]
LPIPS: Higher means further/more different. Lower means more similar.

**Comment by silviapoletti** [comment]
C:\Users\Silvia^ Poletti\Documents\VirtualEnv\Metriche\Scripts\activate.bat
